### ISSUE TITLE
Error!

### ISSUE THREAD

**Issue by QuestionPython** [Aversiste/substr#1]
$ gcc -v
------------
```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.1-2ubuntu2' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.1 20160929 (Ubuntu 5.4.1-2ubuntu2) 
```

------------

$ gcc 4.c -o 4 -O3 -std=c99 
------------
```
4.c:8:8: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘void’
 __dead void usage(void);
        ^
4.c: In function ‘main’:
4.c:19:15: warning: implicit declaration of function ‘getopt’ [-Wimplicit-function-declaration]
  while ((ch = getopt(argc, argv, "")) != -1)
               ^
4.c:22:4: warning: implicit declaration of function ‘usage’ [-Wimplicit-function-declaration]
    usage();
    ^
4.c:25:10: error: ‘optind’ undeclared (first use in this function)
  argc -= optind;
          ^
4.c:25:10: note: each undeclared identifier is reported only once for each function it appears in
4.c:36:8: warning: implicit declaration of function ‘strtonum’ [-Wimplicit-function-declaration]
  pos = strtonum(argv[1], 1, slen, &errstr);
        ^
4.c: At top level:
4.c:55:8: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘void’
 __dead void
        ^
```

**Comment by tleguern** [comment]
Hi,

It should build fine now, I tested the build on Ubuntu 14 with gcc 4.8.4. Can you tell me if it's also good for you ?

Thanks.

**Comment by tleguern** [comment]
No reply since nearly a year, bye bye.
